dashbase:
  https: false
  ingress:
    enabled: true
    host: 127.0.0.1.xip.io

  services:
    grafana:
      image: dashbase/grafana:nightly

    prometheus:
      storage:
        size: "30Gi"

    influxdb: # OPTIONAL; only necessary when using monitoring stack is deployed in a different K8s cluster from Dashbase
      enabled: false
      storage:
        size: "30Gi"
      environment:
        INFLUXDB_DATA_CACHE_MAX_MEMORY_SIZE: 2g
        INFLUXDB_ADMIN_USER: dashbase_monitor
        INFLUXDB_ADMIN_PASSWORD: dashbase_monitor
