dashbase:
  https: false
  ingress:
    enabled: true
    host: 127.0.0.1.xip.io
  accounts:
    prometheus: true
  services:
    prometheus:
      enabled: true
    pushgateway:
      enabled: true
    grafana:
      enabled: true
    alertmanager:
      enabled: false
    influxdb:
      enabled: true