dashbase:
  https: false
  ingress:
    enabled: true
    host: chaotest.dashbase.io

  services:
    grafana:
      image: dashbase/grafana:nightly

    prometheus:
      storage:
        size: "30Gi"

    influxdb:
      storage:
        size: "30Gi"
      environment:
        INFLUXDB_DATA_CACHE_MAX_MEMORY_SIZE: 2g
        INFLUXDB_ADMIN_USER: dashbase_monitor
        INFLUXDB_ADMIN_PASSWORD: dashbase_monitor