---
nightwatch_version: 1.0.0-rc11

prometheus_pushgateway_enable: False
prometheus_local_exportor_url: http://localhost:29273/metrics
prometheus_pushgateway_url: http://localhost/metrics/job/filebeat/instance/{{ ansible_hostname }}

telegraf_agent_version: 1.9.5
telegraf_agent_version_patch: 1
telegraf_agent_interval: 10
telegraf_agent_debug: False
telegraf_agent_round_interval: True
telegraf_agent_flush_interval: 10
telegraf_agent_flush_jitter: 0

telegraf_agent_logfile: "/var/log/telegraf/telegraf.log"
telegraf_agent_omit_hostname: False

telegraf_global_tags: []

telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["http://localhost:8086"]
      - database = "telegraf"
      - precision = "10s"

# defaults - /etc/telegraf/telegraf.conf
telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = true
  - plugin: disk
  - plugin: io
  - plugin: mem
  - plugin: net
  - plugin: system
  - plugin: swap
  - plugin: netstat
  - plugin: processes
  - plugin: kernel

# extra configuration - /etc/telegraf/telegraf.d/*
telegraf_plugins_extra: {}
telegraf_plugins_extra_exclusive: False

# RedHat specific settings for convenience
telegraf_redhat_releasever: "$releasever"

telegraf_yum_baseurl:
  amazon: "https://repos.influxdata.com/centos/6/$basearch/stable"
  centos: "https://repos.influxdata.com/rhel/{{ telegraf_redhat_releasever }}/$basearch/stable"
  default: "https://repos.influxdata.com/{{ ansible_distribution|lower }}/{{ telegraf_redhat_releasever }}/$basearch/stable"
  redhat: "https://repos.influxdata.com/rhel/{{ telegraf_redhat_releasever }}/$basearch/stable"

# Http proxy for package control tools
http_proxy:
https_proxy:
